spring:
  main:
    banner-mode: "off"
  data:
    mongodb:
      database: crm
      uri: "mongodb://localhost:27017/crm"
app:
  local: true

my:
  url: "http://todo"
  api:
    search: "todo"

server:
  servlet:
    context-path: "/TODO"
  port: 8080

auth:
  verifyToken: true
  key: "216d07cc0a0ba94c43cd38f15f68c7bd"
  url: "https://api.stg.hype.it"
  path: "/internal/apiwebservices/multihypelegacyservice/session"
  tokenHeaderName: "auth-token"
  skipUserDataQueryParamName: "skipUserData"
  skipUserDataQueryParamValue: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.apache.http: INFO
    httpclient.wire: INFO
    org.apache.http.client.protocol.ResponseProcessCookies: ERROR
    org.apache.kafka: WARN
    org.mongodb.driver: INFO
    it.hype: DEBUG