spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/crm"
      database: crm
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: Europe/Rome

springdoc:
  swagger-ui:
    urls:
      - name: Digital Euro - PROD
        url: /openapi/deps-api.yaml
      - name: Digital Euro - LOCAL
        url: /openapi/desp-api-local.yaml

server:
  port: 8080
  servlet:
    context-path: "/TODO"

app:
  local: true

auth:
  verifyToken: true
  key: "216d07cc0a0ba94c43cd38f15f68c7bd"
  url: "https://api.stg.hype.it"
  path: "/internal/apiwebservices/multihypelegacyservice/session"
  tokenHeaderName: "auth-token"
  skipUserDataQueryParamName: "skipUserData"
  skipUserDataQueryParamValue: true

my:
  url: "http://todo"
  api:
    search: "todo"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.security: INFO
    org.apache.http: INFO
    httpclient.wire: INFO
    org.apache.http.client.protocol.ResponseProcessCookies: ERROR
    org.apache.kafka: WARN
    org.mongodb.driver: INFO
    it.hype: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full

management:
  endpoints:
    web:
      exposure:
        include: "*"
