apiVersion: #{hpa.version}#
kind: HorizontalPodAutoscaler
metadata:
  name: #{deploymentName}#
  namespace: #{namespace}#
  labels:
    app: #{deploymentName}#
    type: hpa
spec:
  scaleTargetRef:
    apiVersion: #{deployment.version}#
    kind: Deployment
    name: #{deploymentName}#
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85