variables:
  - name: logLevel
    value: "info"
  - name: tolerations
    value: >
      tolerations:
             - key: GeneralPurpose
               operator: Equal
               value: "true"
               effect: NoSchedule